### ISSUE TITLE
配布方法の検討

### ISSUE THREAD

**Issue by Nanashia** [japari-os/japari_os#1]

**Comment by Nanashia** [comment]
ですこーどから加筆転記

isoに同梱
- Ubuntuイメージを書き換えてisoごと配布。比較的簡単。
- GB単位のファイルなので配布方法は工夫する必要がある。(編集済)
- インストーラーのカスタマイズができる

zip
- 配布が簡単。
- /usr/shareなどの編集はroot権限が必要なのでユーザーに特権ユーザーになって適切な場所に解凍してもらう手間が必要
  - 特に/bootなどは一歩間違えると起動しなくなる

deb
- apt-get(dpkg -i)で入れるインストールパッケージで配布する
- DLしてダブルクリック or $ sudo dpkg -i package.deb みたいな感じで入れる
- インストールスクリプトを描く必要がある（＝書ける）。柔軟だけどちょっと大変
- dependencyを設定できるので他のソフトウェア(DesktopEnvironmentなども同時にインスコできる)

ppa経由で配布
- apt-get installで上記のdebをインスコ出来るようにする
- ppaの運用が必要。

**Comment by kasugai-isoya** [comment]
自分としてはイメージファイル(iso)に賛成ですね。ファイルサイズはばかにならないけど一番汎用的というか、安定していますし。

**Comment by Nanashia** [comment]
ふむふむ。確かに毎回クリーンインストールなので、テストは簡単で安定はすると思います。
ただ、Ubuntuのリリースに追従するのが面倒になるデメリットが気になります。

**Comment by Nanashia** [comment]
メモ: https://help.ubuntu.com/community/LiveCDCustomization

**Comment by Nanashia** [comment]
LiveImageを自動化するやつ：
https://debian-live.alioth.debian.org/live-manual/stable/manual/html/live-manual.en.html
それを更に自動化するやつ（GPL）：
https://github.com/UbuntuBudgie/budgie-remix-iso-builder
行けそうな気がしてきた

**Comment by hellcat-friends** [comment]
配布方法なんですが、現状元になるisoが1.5GBあるのでここでは差分だけ管理してisoイメージと全ソースを別の場所で配布が良いと思います。

**Comment by Nanashia** [comment]
@hellcat-friends コメントありがとうございます。
個人的にはisoはtorrentを使えばひとまず撒けないことは無いと思っています。
> 全ソースを別の場所で配布
ということは本当に生データか、debパッケージで配布のどちらかになるという理解ですが合っていますでしょうか？

**Comment by Nanashia** [comment]
Discordのほうで deb および iso の方針で良さそうという話になりましたので
こちらはcloseします。
